version: "3.9"

services:
  db:
    image: postgres:16
    container_name: kopi-db
    restart: always
    environment:
      POSTGRES_USER: kopiadmin
      POSTGRES_PASSWORD: kopipass123
      POSTGRES_DB: kopiceban
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: kopi-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kopiceban.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
